### ISSUE TITLE
How good with React do you need to be to use React-Sketch?

### ISSUE THREAD

**Issue by arturogh** [jem-computer/ama#7]
I'm beginning to dabble into React and can sort of follow along what's published in reactsketch.app, so wondering what coding proficiency this targets :)?

**Comment by jem-computer** [comment]
it's difficult for me to say, because one of the things I'm not good at is education — as soon as I learn something I forget the process I went through to learn it :(

that said -
1) being inspired by create-react-app etc we've tried to make the build process as seamless as possible so you don't have to worry about webpack configs etc
2) all of the examples use modern ES6 - if you're not familiar with arrow functions, destructuring, imports etc it might be confusing. we should add ES5 examples or tutorials too to help learning
3) I'd love for you to give it a go and let me know what you slip up on so we can make it better :)
